[PATHS]
# PROJECT_ROOT sẽ được xác định tự động trong code bằng Path.cwd().parent
# Các đường dẫn dưới đây là tương đối so với PROJECT_ROOT
DATA_DIR = dataset
OUTPUT_DIR = output
TRAIN_FILE = dataset/sales.csv
TEST_FILE = dataset/sample_submission.csv
OUT_FILE = output/submission.csv

[VALID]
split_date = 2022-01-01

[SETTINGS]
N_TRIALS = 30
# Full cores
N_JOBS = -1 
TARGET_COLS = Revenue, COGS
